### ISSUE TITLE
When running the App how do you switch between shaders?

### ISSUE THREAD

**Issue by CreateTheImaginable** [jVirus/SceneShadertoy#4]
When running the App how do you switch between geometry shaders like the Bubble, Chemical, and Ripple shaders in the ( ios-scenekit-shadertoy/SceneShadertoy/Shaders/Geometry/ ) Geometry folder?

**Comment by eleev** [comment]
Sorry for the late reply. There is no way at the moment to switch between the shaders, unfortunately. However, I will add it to the `todo` list. 

Thanks!

**Comment by eleev** [comment]
It’a been a while since I wrote an answer, please reopen the issue if you have any questions or comments.

Again, thank you for your input, I appreciate your interest and your question will be used to further improve the project.
